### PR TITLE
feat: Update from fork

### PR DESCRIPTION
**Pull request by Akryum**

### CODE REVIEW

**Comment by Akryum** [comment]
Not sure why the React doesn't work, is it expected? @JorgenVatle

**Comment by JorgenVatle** [comment]
Hey there, sorry for the late response!

So React compatibility is still a work in progress. It's primarily related to the issues outlined in https://github.com/JorgenVatle/meteor-vite/issues/33.

**Comment by JorgenVatle** [comment]
Got some fixes lines up for addressing the issues with React! 🎉

@Akryum Looks like I didn't accept your invite for the repository in time. 😅 
I'll submit the changes as a pull request to this draft branch in the meantime so we can start getting things in order.

**Comment by JorgenVatle** [comment]
Pulled in changes from #45, addressing the non-functional React example and a couple improvements to the build, test and linting workflows.

This should now be good to go to merge into `main`.

For the todos highlighted in #43 I'll start working on a separate pull request addressing those changes individually.

**Comment by Akryum** [comment]
👀 🚀

**Pull request merged**
