### PR TITLE
feat: Add testing suite to example app, fix bundler edge-cases with default exports, module links and relative wildcard exports

### PR DESCRIPTION
**Pull request by JorgenVatle**
## Fixes
- [x] #27 
- [x] #26 
- [x] #21
- [x] #8
- [x] Closes #28 
- [x] Closes #29

## Additions
- TypeScript type export for the Vite config using [`zodern:types`](https://github.com/zodern/meteor-types)

image

### CODE REVIEW

**Comment by JorgenVatle** [comment]
I'll go ahead and add a GitHub Actions workflow for validating that builds are at the very least passing. 
If you feel it's not a good fit, you should have write permissions on the branch to remove the workflow @Akryum 🙌

The pull request should be ready to be merged now. I've pulled the bundler into a fairly large project with a bunch of Atmosphere dependencies - and production builds appear to be working great. But I'm sure there's a list of other edge cases, not covered by my repo left to be worked out. 😅

**Comment by Akryum** [comment]
I guess this supersedes #28?

**Comment by JorgenVatle** [comment]
That is correct. 👍

**Comment by red-meadow** [comment]
@JorgenVatle , thank you very much for your effort! We are trying to use your fork in our app.

There is still at least one issue related to exports: [this one](https://github.com/Akryum/meteor-vite/issues/27). If you replace `export { default as ReExportedDefault, other, subOther } from './other'` with `export * from './other' `, it doesn't break the app, but `subOther` cannot be imported from `meteor/test:modules` anymore.

**Comment by JorgenVatle** [comment]
I see! Thanks for the heads up. I'll try to find the time hopefully this or next week to look into it.

**Comment by JorgenVatle** [comment]
Alright, @red-meadow, so I've had quite a lot of time to work on this. Maybe a little too much to be honest. 😅

There's a little bit left to do in terms of refactoring and double-checking that there isn't something I've missed. It is functional however in case you want to try it out. 👍

#38

**Comment by red-meadow** [comment]
@JorgenVatle , thank you very much! I'll test it ASAP.

**Comment by JorgenVatle** [comment]
It still hasn't touched a production environment yet, so there's bound to be some breaking issues. But the foundation is there and I don't imagine fixes being more than a line or two 👌 Do let me know how it goes 😄

**Pull request merged**
