### PR TITLE
feat: 🎉 Upgrade Meteor package parser, stub validation and add Vitest

### PR DESCRIPTION
**Pull request by JorgenVatle**
> ## This fork has its own release!
> This fork of the Meteor-Vite bundler has been published as [`jorgenvatle:vite-bundler`](https://github.com/JorgenVatle/meteor-vite). 

# Changes
I've replaced most of the Regex we used to parse Meteor packages with a JavaScript parser to extract the data we need to build up Meteor stubs for Vite, this addresses most of the syntax-based edge cases caused by Meteor's package format.

It also makes it a lot easier to traverse through the bits of the package source we need to build up a good stub, all without having to worry about debugging and refactoring long lines of ungodly regex statements from the last PR. 😅

## Testing 🧪
- Tests can finally run server-side now, and using Vitest, they are blazingly fast.
- Added GitHub workflows and tests validating application builds as well as mocktests for packages with known issues from the current version of Meteor-Vite.
- Meteor package stubs are now validated on the client at runtime. So non-working packages won't just silently fail when you least expect it. Though, that shouldn't happen anymore. Not foolproof, as it will emit false-positive warnings for packages that export undefined. Warnings can be ignored per-package through the Meteor settings.json file.
- Debug mode added to Vite plugin - captures all incoming Meteor package code and outgoing stubs into a mock file format for tests.

## Maintainability ℹ️
- The Vite plugin has been moved into its own package to make it a little easier to work on, particularly for managing dependencies and testing!
- Package parser has been re-written parsing module exports through language tokens rather than Regex - regardless of the format of the Meteor bundle, as long as the methods remain the same, stubs will work the same.
- Converted Vite plugin and workers to TypeScript.
- The Vite bundler and worker packages are versioned using [`changesets`](https://github.com/changesets/changesets)

## Fixes ✅ 
- Re-exports for modules nested under package subdirectories are now imported correctly within Meteor stubs.
- [x] #27 
- [x] #26 
- [x] #21
- [x] #8
- [x] Closes #28 
- [x] Closes #29
- [x] Closes #30

## Added 🎊
- Added Svelte example application
- Vite server startup splash screen

### CODE REVIEW

**Comment by Akryum** [comment]
Hey @JorgenVatle could you add me to the `meteor-vite` package on npm? Thanks!

**Comment by JorgenVatle** [comment]
I certainly can. 👍

Though, this pull request has become a little dated since it was undrafted earlier this summer. 

If it isn't too much work to review on your part, I would like to pull in the latest changes and fixes from the release branch of the fork. 😅

**Comment by Akryum** [comment]
We can do that after I merge this one

**Comment by Akryum** [comment]
@JorgenVatle Are you on Discord by any chance? I also invited you the repo if you want to contribute to it directly. :cat2:

**Comment by JorgenVatle** [comment]
Thank you for trusting me with this! 🙌

Yeah, I'm on Discord every now and then.

**Comment by Akryum** [comment]
Would you mind sending me an friend invite? Or send me your discord username by email

**Pull request merged**
