### PR TITLE
chore: tested Vite and Galaxy

### PR DESCRIPTION
**Pull request by Grubba27**
I've tested standard deployment for meteor & Vite & Vue 3, and here are the results:
Site link: https://vite-and-vue3.meteorapp.com/
Command that I've run:

```bash

meteor deploy vite-and-vue3.meteorapp.com --mongo --free

```
Have not tested SSR yet.
 Really cool having acess to Vite ecossytem! Thanks for this awesome work @Akryum

### CODE REVIEW

**Comment by Akryum** [comment]
Looks like some mime types are wrong. This example CSS file has `text/html`:

image

**Comment by Akryum** [comment]
Looks to be related to some preload directives

**Comment by Grubba27** [comment]
I’ve deployed using the example in the repo. Perhaps there is a vite config that I was supposed to adjust ?

**Comment by Akryum** [comment]
Could you try putting [build.polyfillModulePreload ](https://vitejs.dev/config/build-options.html#build-polyfillmodulepreload) to `false` in the vite config and deploy again? 🙏

**Comment by Grubba27** [comment]
Did it again. I think it is okay.
> Links options
Screen Shot 2022-09-15 at 00 05 01
> Links composition
Screen Shot 2022-09-15 at 00 06 02

**Comment by Akryum** [comment]
I still see the errors on the deployment you shared: 
image

**Comment by Akryum** [comment]
Hmm I've looked at `polyfillModulePreload` and that's not necessary to change it.
Looks like Vite is appending preload tags to the head, but since they don't have `?meteor_js_resource=true` in the URL Galaxy seems to respond with an incorrect mime type. Galaxy should use the correct mime type with the file extensions :(

**Comment by Akryum** [comment]
Could you re-deploy with the new version `0.1.8` I just published?

**Comment by Grubba27** [comment]
I think it worked!! 
Screen Shot 2022-09-15 at 09 12 48

**Comment by Akryum** [comment]
I confirm, I no longer see errors :)

**Pull request merged**
