### PR TITLE
[Examples] add React

### PR DESCRIPTION
**Pull request by afrokick**
I want to add React example.

- [x] use React 18, React DOM
- [ ] use `react-meteor-data` (blocked by https://github.com/Akryum/meteor-vite/issues/2)
- [x] use `ostrio:flow-router-extra` for routing (blocked by https://github.com/Akryum/meteor-vite/issues/3)

### CODE REVIEW

**Comment by afrokick** [comment]
Seems like Meter bundler replace `:` to `_` like `ostrio:flow-router-extra.js` -> `ostrio_flow-router-extra.js` @Akryum

**Comment by afrokick** [comment]
Another problem is meteor package with lazy:true

https://github.com/meteor/react-packages/blob/master/packages/react-meteor-data/package.js#L17

Meteor build it with this content output in `web.browser/packages/react-meteor-data.js`:

```
(function () {



/* Exports */
Package._define("react-meteor-data");

})();
```

**Comment by afrokick** [comment]
Fixed `: -> _` issue on https://github.com/Akryum/meteor-vite/blob/main/packages/vite-bundler/worker-dev.mjs#L19

by adding another one .replace(':','_') after existing replace. But IDK if it a good fix.

**Comment by Akryum** [comment]
Could you try again with 0.1.4?

**Comment by afrokick** [comment]
Thanks, it works.

Any idea how to fix #2 ?

**Comment by Grubba27** [comment]
Hey @afrokick what was the issue that you found to use ``react-meteor-data``? I got excited about the react 18 part :)

**Comment by afrokick** [comment]
@Grubba27 just checked and it doesn't work.

@Akryum I added console.log before this line https://github.com/Akryum/meteor-vite/blob/main/packages/vite-bundler/worker-dev.mjs#L102 and it prints:

```
 {
   packageName: 'mongo',
   hasModuleExports: true,
   moduleExports: '  LocalCollectionDriver: () => LocalCollectionDriver\n',
   id: 'meteor/mongo'
 }
 {
   packageName: undefined,
   hasModuleExports: true,
   moduleExports: undefined, // <-- Why it is undefined while hasModuleExports: true ?
   id: 'meteor/react-meteor-data'
 }

**Comment by gunnartorfis** [comment]
@afrokick is there anything I can do to help this get merged? 😄

**Comment by henriquealbert** [comment]
I got the same error when trying to create an example with Preact
`The requested module '/@id/__x00__meteor/react-meteor-data' does not provide an export named 'useTracker'`
Does this problem related to `react-meteor-data` or `vite:bundler`?

**Comment by henriquealbert** [comment]
I was able to fix the issue mentioned by @afrokick 
But I got another one:
```
Uncaught Error: @vitejs/plugin-react can't detect preamble. Something is wrong. See https://github.com/vitejs/vite-plugin-react/pull/11#discussion_r430879201
    at Hello.jsx:6:11
```
The workaround to make it work was to disable fastRefresh
https://github.com/henriquealbert/meteor-vite-react/blob/main/vite.config.js#L6

**Comment by red-meadow** [comment]
Problems with `react-meteor-data` are probably caused by #21 .
If you fork [react-meteor-data](https://github.com/meteor/react-packages/tree/master/packages/react-meteor-data) and add the line export const A = 'A', it works.
image

**Comment by red-meadow** [comment]
The issue seems to be fixes by #30 .

**Comment by Akryum** [comment]
We now have a React example

**Pull request closed without merging**
